stages:

  create-task-find-last-move:
    cmd: python src/entrypoint.py create-task-find-last-move
    deps:
    - src/tasks/create_task_find_last_move.py
    outs:
    - outputs/tasks/findLastMove.parquet
    params:
    - stages.create-task-find-last-move

  create-task-find-score:
    cmd: python src/entrypoint.py create-task-find-score
    deps:
    - src/tasks/create_task_find_score.py
    outs:
    - outputs/tasks/findScore.parquet
    params:
    - stages.create-task-find-score

  create-task-MLM-on-moves:
    cmd: python src/entrypoint.py create-task-MLM-on-moves
    deps:
    - src/tasks/create_task_MLM_on_moves.py
    outs:
    - outputs/tasks/MLM.parquet
    params:
    - stages.create-task-MLM-on-moves

  # Considered deprecated: I'm not convinced it's helpful for the
  # model while it the most task consuming task to generate
  # create-task-find-best-n-worst-positions:
  #   cmd: python src/entrypoint.py create-task-find-best-n-worst-positions
  #   deps:
  #   - src/tasks/create_task_find_best_and_worst_positions.py
  #   outs:
  #   - outputs/tasks/bestAndWorstPositions.parquet
  #   params:
  #   - stages.create-task-find-best-n-worst-positions

  create-task-find-who-is-winning:
    cmd: python src/entrypoint.py create-task-find-who-is-winning
    deps:
    - src/tasks/create_task_find_who_is_winning.py
    outs:
    - outputs/tasks/whoIsWinning.parquet
    params:
    - stages.create-task-find-who-is-winning

  create-task-sort-FENs:
    cmd: python src/entrypoint.py create-task-sort-FENs
    deps:
    - src/tasks/create_task_sort_FENs.py
    outs:
    - outputs/tasks/sortFENs.parquet
    params:
    - stages.create-task-sort-FENs

  create-task-find-next-best-move:
    cmd: python src/entrypoint.py create-task-find-next-best-move
    deps:
    - src/tasks/create_task_find_next_best_move.py
    outs:
    - outputs/tasks/bestMove.parquet
    params:
    - stages.create-task-find-next-best-move

  merge-tasks-into-dataset:
    cmd: python src/entrypoint.py merge-tasks-into-dataset
    deps:
    - src/data_processing/merge_tasks_into_dataset.py
    - outputs/tasks/findLastMove.parquet
    - outputs/tasks/findScore.parquet
    - outputs/tasks/sortFENs.parquet
    - outputs/tasks/whoIsWinning.parquet
    # - outputs/tasks/bestAndWorstPositions.parquet
    - outputs/tasks/bestMove.parquet
    - outputs/tasks/MLM.parquet
    outs:
    - outputs/raw/
    params:
    - stages.merge-tasks-into-dataset

  generate-poc-dataset:
    cmd: python src/entrypoint.py generate-poc-dataset
    deps:
    - src/data_processing/generate_ready_to_use_dataset.py
    - outputs/raw/
    outs:
    - outputs/poc-dataset/
    params:
    - stages.generate-poc-dataset

  train-poc:
    cmd: python src/entrypoint.py train-poc
    outs:
    - outputs/poc/
    deps:
    - outputs/poc-dataset/
    params:
    - stages.train-poc

  generate-final-dataset:
    cmd: python src/entrypoint.py generate-ready-to-use-dataset
    deps:
    - src/data_processing/generate_ready_to_use_dataset.py
    - outputs/raw/
    outs:
    - outputs/dataset/
    params:
    - stages.generate-ready-to-use-dataset

  train-final-model:
    cmd: python src/entrypoint.py train-final-model
    outs:
    - outputs/model/
    deps:
    - outputs/poc/
    - outputs/dataset/
    params:
    - stages.train-final-model
