stages:

  create-task-find-last-move:
    cmd: python src/entrypoint.py create-task-find-last-move
    deps:
    - src/tasks/create_task_find_last_move.py
    outs:
    - outputs/tasks/findLastMove.parquet
    params:
    - stages.create-task-find-last-move

  create-task-find-score:
    cmd: python src/entrypoint.py create-task-find-score
    deps:
    - src/tasks/create_task_find_score.py
    outs:
    - outputs/tasks/findScore.parquet
    params:
    - stages.create-task-find-score

  create-task-MLM-on-moves:
    cmd: python src/entrypoint.py create-task-MLM-on-moves
    deps:
    - src/tasks/create_task_MLM_on_moves.py
    outs:
    - outputs/tasks/MLM.parquet
    params:
    - stages.create-task-MLM-on-moves

  create-task-find-best-n-worst-move:
    cmd: python src/entrypoint.py create-task-find-best-n-worst-move
    deps:
    - src/tasks/create_task_find_best_and_worst_moves.py
    outs:
    - outputs/tasks/bestAndWorstMoves.parquet
    params:
    - stages.create-task-find-best-n-worst-move

  create-task-find-who-is-winning:
    cmd: python src/entrypoint.py create-task-find-who-is-winning
    deps:
    - src/tasks/create_task_find_who_is_winning.py
    outs:
    - outputs/tasks/whoIsWinning.parquet
    params:
    - stages.create-task-find-who-is-winning

  create-task-sort-FENs:
    cmd: python src/entrypoint.py create-task-sort-FENs
    deps:
    - src/tasks/create_task_sort_FENs.py
    outs:
    - outputs/tasks/sortFENs.parquet
    params:
    - stages.create-task-sort-FENs

  generate-dataset:
    cmd: python src/entrypoint.py generate-dataset
    deps:
    - src/data_processing/generate_dataset.py
    - outputs/tasks/findLastMove.parquet
    - outputs/tasks/findScore.parquet
    - outputs/tasks/sortFENs.parquet
    - outputs/tasks/whoIsWinning.parquet
    - outputs/tasks/bestAndWorstMoves.parquet
    - outputs/tasks/MLM.parquet
    outs:
    - outputs/dataset
    params:
    - stages.generate-dataset
