stages:

  sample-dataset:
    cmd: python sample_dataset.py
    deps:
    - sample_dataset.py
    outs:
    - outputs/samples

  create-task-find-last-move:
    cmd: python create_task_find_last_move.py
    deps:
    - create_task_find_last_move.py
    - outputs/samples
    outs:
    - outputs/tasks/findLastMove
    params:
    - data.quantity_per_task.find_last_move

  create-task-find-score:
    cmd: python create_task_find_score.py
    deps:
    - create_task_find_score.py
    - outputs/samples
    outs:
    - outputs/tasks/findScore
    params:
    - data.quantity_per_task.find_score

  generate-PGNs:
    cmd: python generate_PGNs.py
    deps:
    - generate_PGNs.py
    - outputs/samples
    outs:
    - outputs/PGNs

  generate-FENs:
    cmd: python generate_FENs.py
    deps:
    - generate_FENs.py
    - outputs/PGNs
    outs:
    - outputs/FENs

  generate-evaluations:
    cmd: python generate_evaluations.py
    deps:
    - generate_evaluations.py
    - outputs/FENs
    outs:
    - outputs/evaluations

  create-task-MLM-on-moves:
    cmd: python create_task_MLM_on_moves.py
    deps:
    - create_task_MLM_on_moves.py
    - outputs/evaluations
    outs:
    - outputs/tasks/MLM
    params:
    - data.quantity_per_task.MLM_on_moves

  create-task-find-best-n-worst-move:
    cmd: python create_task_find_best_n_worst_move.py
    deps:
    - create_task_find_best_n_worst_move.py
    - outputs/evaluations
    outs:
    - outputs/tasks/bestAndWorstMoves
    params:
    - data.quantity_per_task.find_best_n_worst_moves

  create-task-find-whos_winning:
    cmd: python create_task_find_whos_winning.py
    deps:
    - create_task_find_whos_winning.py
    - outputs/evaluations
    outs:
    - outputs/tasks/whoIsWinning
    params:
    - data.quantity_per_task.find_who_is_winning

  create-task-sort-FENs:
    cmd: python create_task_sort_FENs.py
    deps:
    - create_task_sort_FENs.py
    - outputs/evaluations
    outs:
    - outputs/tasks/sortFENs
    params:
    - data.quantity_per_task.sort_FENs
